name: 'extract-changelogs'
description: 'Extract changelog from mono repo and returns slack formatted message'
author: 'vikas-cldcvr'
inputs:
  changelog-files-config: 
    required: true
    description: 'keya-value object of packagename and changelog file path'
    default: '{}'
  released-package-versions: 
    required: true
    description: 'keya-value object of packagename and version file path'
    default: '{}'
  outputs:
    changelog:
      description: 'Converted Slack mrkdwn text'
runs:
  using: 'node16'
  main: 'dist/index.js'
